name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install build tools and cppcheck
      run: sudo apt-get update && sudo apt-get install -y build-essential cppcheck

    - name: Run static analysis
      run: make check

    - name: Build the project
      run: make

    - name: Run tests
      run: make test
